### ISSUE TITLE
easy english

### ISSUE THREAD

**Issue by vpoulailleau** [adamchainz/flake8-comprehensions#141]
Your project seems a good idea.

I have a remark though. I'm not a native English speaker, and I think that the README might lead to some confusion:

> `list(f(x) for x in foo)` is better as `[f(x) for x in foo]`

can be understood as

`list(f(x) for x in foo)` is better than `[f(x) for x in foo]`

I would consider using this instead:
Don't use `list(f(x) for x in foo)`, use `[f(x) for x in foo]`

Or

Don't | Do
------- | ---
`list(f(x) for x in foo)`|`[f(x) for x in foo]`

Feel free to reject my issue, or comment it.

**Comment by adamchainz** [comment]
When you say it "can be understood", does that mean you initially misunderstood it, or you just recognize that others might make that error?

I have made #142 as a way of rewording the README, can you review it to see if it makes sense for you?

**Comment by vpoulailleau** [comment]
I misunderstood because I read too fast (and I'm not used to see this kind of sentence). I first thought that you said the opposite of what you wanted to say, and I was writing an issue. I then saw my mistake.

#142 looks great to me. Thanks.

**Comment by adamchainz** [comment]
Merged, thanks!
