### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by danpalmer** [adamchainz/flake8-comprehensions#15]
Hi, I've just noticed that the version on GitHub is not on PyPI. Could you do a new release please?

**Comment by adamchainz** [comment]
**1.2.0** released: https://pypi.python.org/pypi/flake8-comprehensions

**Comment by adamchainz** [comment]
Sorry there, I was kind of stalling for #7 but then forgot about it...

**Comment by danpalmer** [comment]
Thanks!
