### ISSUE TITLE
Add the `iter()` builtin to checker `C407`

### ISSUE THREAD

**Issue by sauravsrijan** [adamchainz/flake8-comprehensions#152]
#### `iter()`  
> Example:
> ```
>even_iterator = iter([i for i in range(1,100) if i%2 == 0])
>```
>This can be directly written as: 
>```
>even_iterator = iter(i for i in range(1,100) if i%2 == 0)
>```

**Comment by adamchainz** [comment]
I think there might be a subtle change in the possible exceptions thrown as per #59

**Comment by adamchainz** [comment]
See also #58

**Comment by sauravsrijan** [comment]
Oh! Alright.

But for the existing cases in `C407`, why are they raised only for list comprehension?
Aren't they valid for different comprehensions too?  example: set comprehension

**Comment by adamchainz** [comment]
They probably are, PR's welcome. If you make a PR please ensure you add a changelog note, update the documentation, and create  tests.

**Comment by joaoe** [comment]
`iter(<comprehension>)` is redundant.
`(<comprehension>)` is enough and produces a generator.

**Comment by adamchainz** [comment]
You're right, since a generator is its own iterator:

```
In [3]: (x for x in range(1))
Out[3]: <generator object <genexpr> at 0x106df2e40>

In [4]: iter(x for x in range(1))
Out[4]: <generator object <genexpr> at 0x106df2eb0>
```

**Comment by adamchainz** [comment]
@sauravsrijan released a fix to your issue in version 3.2.0: https://pypi.org/project/flake8-comprehensions/3.2.0/

As per comments on #58 and #59, I'm closing this issue, since it's not generally safe due to the change in possible raised exception from `IndexError` to `StopIteration`.

**Comment by joaoe** [comment]
> I'm closing this issue, since it's not generally safe due to the change in possible raised exception from `IndexError` to `StopIteration`.

#59 deals with `<expr>[0]`. This issue is just about a plain iter, which always raises a `StopIteration`.

```
>>> next(iter([1 for _ in ""]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
>>> next(1 for _ in "")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
StopIteration
```

**Comment by adamchainz** [comment]
You're right!
