### ISSUE TITLE
Set of a list comprehension/literal

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/flake8-comprehensions#2]
Suggested by @tolomea

* `set([f(x) for x in foo])` -> `{f(x) for x in foo}`
* `set([1, 2])` -> `{1, 2}` (n.b. can't complain about empty list in this way though since `{}` = empty dict - myabe can do `set([])` -> `set()` though)

**Comment by tolomea** [comment]
dict([(a,b) for a,b in foo]) and dict([(1,2), (2,3)]) as well
