### ISSUE TITLE
False positive C416

### ISSUE THREAD

**Issue by kalekseev** [adamchainz/flake8-comprehensions#203]
With version 3.1.1 I get `C416 Unnecessary list comprehension - rewrite using list().` for this code `x = [(a, b, 1) for (a, b) in []]`
I think linter just checks that first two params of "(a, b, 1)" tuple equal "(a, b)" tuple.

**Comment by adamchainz** [comment]
Fixed in version 3.1.3 earlier today, plaese upgrade. See other report on #196 as well.
