### ISSUE TITLE
Python 2.6 mode

### ISSUE THREAD

**Issue by jayvdb** [adamchainz/flake8-comprehensions#21]
It would be nice if a project can specify that they need '2.6' support, and only rules that dont break 2.6 support would be active.

For example, the set rules in #2 rely on Python 2.7 syntax.
As a result, we need to turn off those codes, despite those codes having many good rules that are applicable and valid on Python 2.6, because a few rules are not.

https://gerrit.wikimedia.org/r/#/c/302103/

It would be especially lovely if you supported `min-version = 2.6` that [flake8-future-import](https://pypi.python.org/pypi/flake8-future-import) uses, which also allows for other versions to have specific syntax that affects these rules.

**Comment by adamchainz** [comment]
I'm sorry I've only developed this plugin to support Python 2.7. If you want this support please make a pull request, but beware that the last release of 2.6 is nearly 8 years ago!!

**Comment by jayvdb** [comment]
Im happy to put a PR together for this, sometime this week.

**Comment by adamchainz** [comment]
I've just discovered that the latest `flake8` dropped Python 2.6 compatibility. Sure you can't upgrade? 😁

**Comment by jayvdb** [comment]
I wish. We have de-supported it on our stable release, but are supporting it on master as one developer needs it due to Redhat.

**Comment by adamchainz** [comment]
Can't your developer just use a second python interpreter on his machine? At YPlan we use [vagrant](https://www.vagrantup.com/) for consistent development environments.

**Comment by jayvdb** [comment]
Again, no, and sorry I didnt explain it in sufficient detail.  His problem is he needs to use the software on a locked down corporate box with strict rules around usage. Kinda hard to tell a core developer he cant use the app he helped build anymore, because flake8 decided his use case doesnt need to be supported in the current release. We support Python 2.6 only on master because there he can fix any bugs he encounters.

**Comment by adamchainz** [comment]
😿
