### ISSUE TITLE
Add filter, map, reduce to list of functions that take a generator in C407.

### ISSUE THREAD

**Issue by joaoe** [adamchainz/flake8-comprehensions#212]
filter 
https://docs.python.org/3/library/functions.html#filter
map
https://docs.python.org/3/library/functions.html#map
reduce or functools.reduce
https://docs.python.org/3/library/functools.html#functools.reduce

Thank you.

**Comment by adamchainz** [comment]
Hi,

Which rules would this affect?

Also since this is probably not a large change. Could you look into adding a PR with tests?

Thanks,

Adam

**Comment by joaoe** [comment]
Hi. I clarified the title. Rule C407

**Comment by adamchainz** [comment]
Released in version 3.2.0: https://pypi.org/project/flake8-comprehensions/3.2.0/

I didn't include `reduce` since it's not a builtin, and it requires a lot more work to figure out if `functools.reduce` is imported in the current scope.
