### ISSUE TITLE
Unnecessary list literal that should be a tuple

### ISSUE THREAD

**Issue by jayvdb** [adamchainz/flake8-comprehensions#22]
This isnt strictly a case for comprehension, but seems to fit nicely with your other errors.
 `sorted([1, 3, 2])` is an unnecessary list, that should be replaced with a tuple as the iterable processor `sorted` (and any other readonly processor) doesnt need a list.

i.e. this should be

`sorted((1, 3, 2))`

**Comment by adamchainz** [comment]
But if the data is a literal, why not make it in sorted order already, i.e. `(1, 2, 3)`, and save the relatively large overhead of a function call?

**Comment by jayvdb** [comment]
The data could be three variables.

**Comment by adamchainz** [comment]
Ok fair point. It's also marginally faster:

```
In [4]: %timeit list(sorted([1,2,3]))
The slowest run took 4.16 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 923 ns per loop

In [5]: %timeit list(sorted((1,2,3)))
The slowest run took 4.35 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 729 ns per loop
```

I'll look at adding this.

**Comment by jdufresne** [comment]
Stylistically, I'm not convinced a tuple should be preferred over a list. Semantically speaking, the example is of unknown length of uniform elements. This is the intended use of a list, not a tuple.

See [Python's documentation on the matter](https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences):

> Though tuples may seem similar to lists, they are often used in different situations and for different purposes. Tuples are immutable, and usually contain a heterogeneous sequence of elements that are accessed via unpacking (see later in this section) or indexing (or even by attribute in the case of namedtuples). Lists are mutable, and their elements are usually homogeneous and are accessed by iterating over the list.

**Comment by pope1ni** [comment]
@jdufresne I think a tuple does make more sense here. `sorted` always returns a list anyway regardless of input. A list _literal_ (which is what the reporter is referring to) makes this slower than a tuple _literal_. Also the list or tuple passed directly as an argument to the function is never going to see reuse, so the point about mutability is moot.

Perhaps this also applies to other builtins too, e.g. `enumerate`?

**Comment by adamchainz** [comment]
Coming back to this old issue...

I just wrote a blog post about how I prefer lists over tuples in most cases: https://adamj.eu/tech/2019/07/05/tuples-versus-lists-in-python/

I am not sure a linter rule to encourage tuple literals for the case discussed here is generally worth it. Yes they're marginally faster to construct, but probably only 0.1% of Python projects can take advantage of such a speedup. In such cases I hope the authors of such code are profiling vigorously or even considering another use case or looking at other languages.

Therefore, closing issue.
