### ISSUE TITLE
reversed(sorted(x)) is not the same thing as sorted(x, reverse=True)

### ISSUE THREAD

**Issue by gimbo** [adamchainz/flake8-comprehensions#234]
Issue #60 recommended introducing a new rule suggesting that `reversed(sorted(...))` be replaced with `sorted(..., reverse=True)`, and that's now been released (C413).

However, they are not equivalent. `sorted()` always returns a list (an iterable), but `reversed()` returns an `listreverseiterator` object (an iterator).

Thus, if we use `sorted(..., reverse=True`, we get a result which may be iterated over multiple times:

```
>>> x = sorted([2,4,5], reverse=True)
>>> list(x)
[5, 4, 2]
>>> list(x)
[5, 4, 2]
```

Whereas if we use `reversed(sorted(...))`, we get a result which may be iterated over just once:

```
>>> y = reversed(sorted([2,4,5]))
>>> list(y)
[5, 4, 2]
>>> list(y)
[]
```

This is nitpicking, and it's probably less of a problem than if it was the other way around (at least the recommended change shouldn't introduce any logical errors this way round), so perhaps this is a WONTFIX — but I thought it was worth pointing out.

**Comment by adamchainz** [comment]
Hi @gimbo 

Yes you're right there is a subtle difference. I can imagine the change is unsafe in rare cases where the result is differentiated with e.g. `isinstance(x, typing.Iterator)`.

I would like to keep the suggestions from flake8-comprehensions completely equivalent though, so perhaps it should be removed.

I guess you didn't experience any bug because of this though?

**Comment by gimbo** [comment]
No, I didn't experience a bug, in fact I didn't come across this directly at all... What actually happened was that the plugin told me about a couple of instances of `list(sorted(...))` in my codebase, which surprised me because I had thought that `sorted()` returned an iterator, not a list — I've only been programming in python since 1999 so I'm not sure how I missed that one - thanks for the top!

So that got me scratching my head, wondering what other assumptions I had wrong, and I started thinking about `reversed()` and a bit of investigation led me to this... :-)

**Comment by adamchainz** [comment]
Ok cool. Glad it was educational! It has certainly been educational to build and maintain :)

I'm going to close this for now, but if this causes a bug I will remove the rule.
