### ISSUE TITLE
Performance implications of C412

### ISSUE THREAD

**Issue by javierhonduco** [adamchainz/flake8-comprehensions#253]
Hi,

We have some code that looks like:
```python
def is_valid(vm: str) -> bool:
  return vm in {machine for machine in machines}
```

And we got this lint error:

> C412: Unnecessary (dict/list/set) comprehension - ‘in’ can take a generator.

This code is not particularly performance sensitive, so using a set or a generator probably does not make a big difference (and in fact probably the generator is faster!), but I am concerned that in other cases, applying the lint suggestion might result in a `O(n)` search rather than an amortised constant time.

In the original PR (#166) @adamchainz mentioned that [checking for inclusion in some generators, such as `range` is optimised](https://stackoverflow.com/questions/30081275/why-is-1000000000000000-in-range1000000000000001-so-fast-in-python-3) and that converting to a list / set and checking for including incurs in more memory copies and slower time overall, but as far as I know this is not true in other cases such as the one we bumped into.

Maybe the lint message could be updated so folks are aware that it might have a performance penalty?

Cheers,

**Comment by adamchainz** [comment]
> I am concerned that in other cases, applying the lint suggestion might result in a O(n) search rather than an amortised constant time.

But construction of the dict/list/set comprehension is O(n). If it's on the right hand side of an `in`, it's temporary and discarded. Using `in <genexpr>` avoids constructing the whole set and returns early.

In your case this is quite noticeable:

```
In [1]: machines = list(str(x) for x in range(10000))

In [2]: def is_valid_set(vm):
   ...:   return vm in {machine for machine in machines}
   ...:

In [3]: %timeit is_valid_set("1234")
378 µs ± 5.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [4]: def is_valid_gen(vm):
   ...:   return vm in (machine for machine in machines)
   ...:

In [5]: %timeit is_valid_gen("1234")
52.2 µs ± 128 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by javierhonduco** [comment]
Thanks for the quick reply!

> I'm willing to be proven wrong but I don't think you've found a case here that there's a performance penalty.

I agree with you, in that case we are unnecessarily creating a list for not good reason and this can be avoided. Sorry that my example was not very good 😓.

Imagine code that runs in a service that periodically fetches some configuration data that we deserialise as a list. We can't deserialise as any other data-structure, due to how the internals of this library works, so we will always pay that price, think of something like Protocol Buffers or Thrift.

We can convert this list to a set, once every time we fetch said config, and then check for inclusion in said function, which is called many more times than the configuration is fetched, which would be more efficient if it's a set.

Just a quick benchmark: 
```python
In [1]: def gen_machines(howmany):
   ...:     machines = list(str(x) for x in range(howmany))
   ...:     machines_set = set(x for x in machines)
   ...:     return machines, machines_set
   ...:

In [2]: machines, machines_set = gen_machines(1_000)

In [3]: %timeit "not_there" in machines
13.4 µs ± 99 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [4]: %timeit "not_there" in machines_set
41.4 ns ± 1.62 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
In [5]: machines, machines_set = gen_machines(1_000_000)

In [6]: %timeit "not_there" in machines
14.4 ms ± 329 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: %timeit "not_there" in machines_set
41.3 ns ± 1.52 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

Anyhow, I filed this issue because I thought that it might be good to have it tracked even if no changes will be done as this is sort of an edge case 😊

**Comment by adamchainz** [comment]
This lint rule is only concerned with lines like `x in {y for y in ...}`. In such cases it's never necessary to have the intermediate dict/list/set comprehension. As soon as you store the dict/list/set in a variable like `x in some_set` the lint rule also won't detect it. I don't think it's really an edge case for the lint rule per se, if the dict/list/set is useful in more than one place the programmer will probably DRY it into a variable already.

**Comment by javierhonduco** [comment]
In this case it is, because we do the attribute access that I mentioned above, like:

```python
from another_file import machines

machine_names = {machine.name for machine in machines}

def is_valid(vm: str) -> bool:
  return vm in machine_names
```

Correct me if I got something wrong

**Comment by adamchainz** [comment]
Yes that looks like it would work.

**Comment by javierhonduco** [comment]
Mm will investigate a bit more later, might be a behaviour particular to our environment, because I can reproduce: 

```
>>> Lint for $file:

   Advice  (FLAKE8) C412
    Unnecessary set comprehension - 'in' can take a generator.

             531
             532     @classmethod
             533     def is_valid(cls, vm: VM) -> bool:
    >>>      534         return vm.name in {x.name for x in machines}
```

But tried with the same version on another machine, and I can't reproduce... Should have tried before on a more standard environment before opening the issue. Sorry about this.

**Comment by adamchainz** [comment]
I'm not saying this doesn't reproduce.

As you've implemented your method, in a single line, it will be faster using the generator form:

`return vm.name in (x.name for x in machines)`

This avoids creating the set on every function call.

But since you're using the same global `machines` variable, you can do as you suggested and create a set in your module:

```
machine_names = {x.name for x in machines}
```

Then make the method use:

```
return vm.name in machine_names
```

But that's not something a lint rule can spot.

**Comment by javierhonduco** [comment]
Oh, ok, misunderstood you. 

> But that's not something a lint rule can spot.

But yeah, the issue is that the lint, in its current form might make people change it from a set to a generator, with the performance implications this has. That's why I suggested the possibility of mentioning that in the lint message.

BTW, I did not manage to repro before because of a versioning problem. With
```shell
versions="1.0.0 1.1.0 1.1.1 1.2.0 1.2.1 1.3.0 1.4.0 1.4.1 2.0.0 2.1.0 2.2.0 2.3.0 3.0.0 3.0.1 3.1.0 3.1.1 3.1.2 3.1.3 3.1.4 3.2.0 3.2.1 3.2.2 3.2.3"
for version in $versions; do
 python3 -m pip uninstall flake8 --yes > /dev/null 2>&1
 python3 -m pip install flake8-comprehensions==$version > /dev/null 2>&1

  echo "Trying version: $version"
  flake8 repro.py
  echo
done
```

Seems like this repros in `3.2.0`, `3.2.1`, `3.2.2`, and `3.2.3`.

**Comment by adamchainz** [comment]
> But yeah, the issue is that the lint, in its current form might make people change it from a set to a generator, with the performance implications this has. 

For the single line form, it only improves performance. So I won't change it.

> I did not manage to repro before because of a versioning problem

Your repro test is hardly a surprise since the check was only extended to sets in 3.2.0. https://github.com/adamchainz/flake8-comprehensions/blob/master/HISTORY.rst#320-2020-01-20
