### ISSUE TITLE
Extend C41x to detect for _ in list(dict.values())

### ISSUE THREAD

**Issue by Lattay** [adamchainz/flake8-comprehensions#290]
Hello,
I inherited a code with a lot of pattern like this:
```python
for val in list(some_dict.values()):
    do_something(val)
```

As well as the list comprehension counterpart.
As this plugin helped me a lot to catch a lot of other list comprehension and list/set/dict abuse, I wondered if such a pattern could be added to C411 (or another code).

**Comment by adamchainz** [comment]
Hi,

Yes, we could do this. I think it would want another code.

I don't have time to look into this right now, but if you make a PR I'll review. To start, check out the `ast` module in Python's standard library and try parsing some examples to see what the parsed tree looks like for this pattern.

Thanks,

Adam

**Comment by Lattay** [comment]
Thank you, I never done flake8 plug-ins before butI'll look into it.
