### ISSUE TITLE
test_C416_fail_1_list fails

### ISSUE THREAD

**Issue by mcepl** [adamchainz/flake8-comprehensions#313]
When building package for openSUSE, the test suite fails in this one test test_C416_fail_1_list:
```
[   18s] =================================== FAILURES ===================================
[   18s] ____________________________ test_C416_fail_1_list _____________________________
[   18s]
[   18s] flake8dir = <pytest_flake8dir.Flake8Dir object at 0x7fa392a57160>
[   18s]
[   18s]     def test_C416_fail_1_list(flake8dir):
[   18s]         flake8dir.make_example_py("[x for x in range(5)]")
[   18s]         result = flake8dir.run_flake8()
[   18s]         # Column offset for list comprehensions was incorrect in Python < 3.8.
[   18s]         # See https://bugs.python.org/issue31241 for details.
[   18s]         col_offset = 1 if sys.version_info >= (3, 8) else 2
[   18s] >       assert result.out_lines == [
[   18s]             "./example.py:1:%d: C416 Unnecessary list comprehension - rewrite using list()."
[   18s]             % col_offset,
[   18s]         ]
[   18s] E       AssertionError: assert ['./example.p...sing list().'] == ['./example.p...sing list().']
[   18s] E         At index 0 diff: './example.py:1:1: C416 Unnecessary list comprehension - rewrite using list().' != './example.py:1:2: C416 Unnecessary list comprehension - rewrite using list().'
[   18s] E         Full diff:
[   18s] E           [
[   18s] E         -  './example.py:1:2: C416 Unnecessary list comprehension - rewrite using '
[   18s] E         ?                  ^
[   18s] E         +  './example.py:1:1: C416 Unnecessary list comprehension - rewrite using '
[   18s] E         ?                  ^...
[   18s] E
[   18s] E         ...Full output truncated (3 lines hidden), use '-vv' to show
[   18s]
[   18s] tests/test_flake8_comprehensions.py:840: AssertionError
[   18s] =========================== short test summary info ============================
[   18s] FAILED tests/test_flake8_comprehensions.py::test_C416_fail_1_list - Assertion...
[   18s] ======================== 1 failed, 63 passed in 13.74s =========================
```
[Build log](https://github.com/adamchainz/flake8-comprehensions/files/6164276/_log.txt) with all details.

**Comment by adamchainz** [comment]
This test is parameterized based on Python version. See the source for a link to the relevant Python bug. From the build log it looks like you're mixing Python 3.6 and 3.8.

**Comment by mcepl** [comment]
> From the build log it looks like you're mixing Python 3.6 and 3.8.

You misread that build log. I build two packages sequentially, one with Python 3.6, the other with Python 3.8 (that's what we do for around two thousand packages in openSUSE/Factory so don't tell me it is not possible). Nothing gets mixed here.

**Comment by adamchainz** [comment]
Okay - so another thing this does is it spawns a subprocess to run flake8 with the plugin and see if that's working. It looks like the Python 3.8 test is executing the Python 3.6 version of flake8, hence getting different output.

**Comment by mcepl** [comment]
So, couldn't these tests use ``sys.executable`` for running any subprocesses or something?

**Comment by adamchainz** [comment]
Good point - updated in https://github.com/adamchainz/pytest-flake8dir/blob/main/HISTORY.rst#231-2021-03-18

**Comment by mcepl** [comment]
That's different project. This error is in `flake8-comprehensions`, not `flake8dir`. Or did I miss anything?

**Comment by adamchainz** [comment]
It's a dependency used in the tests here.

**Comment by mcepl** [comment]
ok

**Comment by mcepl** [comment]
Works perfectly, thank you.
