### ISSUE TITLE
False type for tree

### ISSUE THREAD

**Issue by kasium** [adamchainz/flake8-comprehensions#352]
### Python Version

3.7.1

### flake8 Version

3.9.2

### Package Version

latest

### Description

Hi,
thanks for adding type hints to the project. 
The type for `ComprehensionChecker.__init__.tree` is `ast.Module`, but should be `ast.AST`.

I'm happy to open a PR if you like

**Comment by adamchainz** [comment]
Released in version 3.6.1.

Did this affect you in any way, or were you just looking at the type hints out of curiosity?

**Comment by kasium** [comment]
Wow, thanks for the fast action!

It affects me in a work project. This project acts as a kind of super-flake8 plugin, so it uses directly the API of great plugins such as flake8-comprehensions. And since it uses type checking, I found this issue

**Comment by adamchainz** [comment]
Ah okay.

It looks to me like the type hints is actually wrong in flake8:

https://github.com/PyCQA/flake8/blob/281f3f8b43106023bf3fb160666384394031a9fd/src/flake8/processor.py#L221

`ast.parse` returns an `ast.Module` in its default mode, exec:

https://github.com/python/typeshed/blob/3ce5502675d3c23394b592f00234fbdfc743a7d5/stdlib/ast.pyi#L159-L167

**Comment by kasium** [comment]
Interesting find. However, flake8 is not a type package (py.typed is not part of the package), therefore mypy doesn't care :-)

**Comment by adamchainz** [comment]
https://github.com/PyCQA/flake8/pull/1376
