### ISSUE TITLE
Incompatibility with flake8 4.0.0

### ISSUE THREAD

**Issue by amrishparmar** [adamchainz/flake8-comprehensions#371]
### Python Version

3.9

### flake8 Version

4.0.0

### Package Version

3.6.1

### Description

`flake8` [4.0.0 was released earlier today](https://github.com/PyCQA/flake8/releases/tag/4.0.0). The current release of `flake8-comprehensions` is not compatible with this new release resulting in an error during the pip installation.

```
ERROR: ResolutionImpossible: for help visit pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

 The conflict is caused by:
    The user requested flake8==4.0.0
    flake8-comprehensions 3.6.1 depends on flake8!=3.2.0, <4 and >=3.0
```

**Comment by adamchainz** [comment]
Fixed in #372, released in 3.7.0 👍
