### ISSUE TITLE
Convert `map(lambda x: expression, iterable)` to `(expression for x in iterable)`

### ISSUE THREAD

**Issue by sweeneyde** [adamchainz/flake8-comprehensions#405]
### Description

`map(f, iterable)` has great performance when `f` is a built-in function, and it makes sense if your function already has a name. But if you need to introduce a lambda, it's better (i.e., more readable and faster) to use a generator expression -- no function calls needed.

Good:
```
for y in map(my_function_that_already_exists, it):
    ...
ys = list(map(my_function_that_already_exists, it))
ys = set(map(my_function_that_already_exists, it))
etc.
```

Suggestions:
```
# Bad:
map(lambda x: x**2, iterable)
# change to:
(x**2 for x in iterable)

# Bad:
list(map(lambda x: x.attr, iterable))
# change to:
[x.attr for x in iterable]
# OR change to:
y = list(map(operator.attrgetter("attr"), iterable))

# Bad:
z = map(lambda x: f(x), iterable)
# change to:
z = map(f, iterable)
```

Here are some perf numbers (`deque(..., maxlen=0)` is a fast way to consume an iterable):

```
PS C:\Users\sween> py -3.8 -m pyperf timeit -s "from collections import deque" "deque(map(lambda x: -x, range(1_000_000)), maxlen=0)"
Mean +- std dev: 85.7 ms +- 1.7 ms

PS C:\Users\sween> py -3.8 -m pyperf timeit -s "from collections import deque" "deque((-x for x in range(1_000_000)), maxlen=0)"

Mean +- std dev: 63.1 ms +- 2.9 ms
```

Similar things hold for `filter()`.

**Comment by adamchainz** [comment]
I think this is legitimate, `map()` is lazy like a generator expression, and `lambda` will always have an overhead. If you'd like to make a PR I'd be happy to review it - please ensure you add docs, a changelog note, and tests.

**Comment by sweeneyde** [comment]
I don't think I'll have the bandwidth for a few weeks, so if you want to, go ahead. If not, I can do it after a while.

**Comment by tusharsadhwani** [comment]
I can make a PR.

**Comment by tusharsadhwani** [comment]
Although there's one small problem: without storing any additional data, `list(map(lambda x: expr, iterable))` will end up raising 2 issues:
- One to rewrite `list(map(lambda x: expr, iterable))` to `[expr for x in iterable]`
- One to rewrite `map(lambda x: expr, iterable)` to `(expr for x in iterable)`

So I'll need to store a set of `list(map(...))` elements that have already been raised. Does that sound right?

**Comment by adamchainz** [comment]
Yup sounds like a good idea

**Comment by joaoe** [comment]
This could also include
`filter(lambda x: expression, iterable)` to `(x for x in iterable if expression)`

**Comment by tusharsadhwani** [comment]
@joaoe the if-clause in that example will pretty much require a separate check imo. I'll make that (and similar filter checks) separately, as C418.
