### ISSUE TITLE
Split dict(name=value) from C408

### ISSUE THREAD

**Issue by joaoe** [adamchainz/flake8-comprehensions#418]
### Description

The C408 warning warns about empty constructors, like dict(), list() and tuple().

However, it lumps together dict(arg=value). This is a very different case. In ym project, there are many cases where the dict(arg=value) syntax is prefered, for isntance, manipulating **kwds, since the key-value pairs are read as if they were function arguments. This syntax also enforces the keys to be python identifiers. And it requires much less boilerplate.
`dict(arg=value)` is less messy than `{"arg": value}`. Some tools, like SonarQube even complain if the string "arg" show up more than 3 times in code and asks to create a variable for it.

So my request is to split that warning into a separate warning like a new C417, or C901 (opinionated warning).

**Comment by adamchainz** [comment]
I don't want to split it.

`dict(arg=value)` does a lot more work than `{"arg": value}`. It essentially constructs the dictionary *twice* - once for the keyword arguments, then once when `dict()` runs. So it runs twice as slow:

```
In [1]: %timeit {"k": "v"}
49.3 ns ± 0.197 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [2]: %timeit dict(k="v")
94 ns ± 0.6 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

If you still prefer `dict()`, just disable the check in your project.

> Some tools, like SonarQube even complain if the string "arg" show up more than 3 times in code and asks to create a variable for it.

THat sounds like a dumb check and I would recommend disabling it.

**Comment by joaoe** [comment]
> THat sounds like a dumb check and I would recommend disabling it.
Amen.
