### ISSUE TITLE
What about adding the walrus operator := ?

### ISSUE THREAD

**Issue by cclauss** [adamchainz/flake8-comprehensions#431]
### Description

The walrus operator can be quite helpful but it is not yet widely adopted.  All the [walrus-related packages on PyPI](https://pypi.org/search/?q=walrus) are either unrelated to `:=` or they actively **_discourage_** its use like https://pypi.org/project/flake8-walrus

It would be cool to have a way to automatically spot places where `:=` could be used to accelerate its adoption.

**Comment by adamchainz** [comment]
I'd be happy to consider concrete proposals where using the walrus would lead to a comprehension/generator expression being faster. Do you have any?

**Comment by joaoe** [comment]
This seems more of a suggestion for flake8-simplify
https://pypi.org/project/flake8-simplify/
