### ISSUE TITLE
Conflicting C416 and C400 rule

### ISSUE THREAD

**Issue by michaeloliverx** [adamchainz/flake8-comprehensions#444]
### Python Version

3.9.12

### flake8 Version

5.0.4

### Package Version

3.10.0

### Description

Reproduction:
```python
from datetime import date

from dateutil.rrule import MONTHLY, rrule

# Unnecessary list comprehension - rewrite using list(). flake8(C416)
datetimes = [dt for dt in rrule(MONTHLY, dtstart=date(2001, 1, 1), until=date(2005, 1, 1))]

# Unnecessary generator - rewrite as a list comprehension. flake8(C400)
datetimes = list(dt for dt in rrule(MONTHLY, dtstart=date(2001, 1, 1), until=date(2005, 1, 1)))

```

**Comment by adamchainz** [comment]
The way C416 wants you to rewrite it is:

```python
datetimes = list(rrule(MONTHLY, dtstart=date(2001, 1, 1), until=date(2005, 1, 1)))
```

not with a generator.

If you think [the docs](https://github.com/adamchainz/flake8-comprehensions#c416-unnecessary-listset-comprehension---rewrite-using-listset) could be improved, please make a suggestion!

**Comment by michaeloliverx** [comment]
> The way C416 wants you to rewrite it is:
> 
> ```python
> datetimes = list(rrule(MONTHLY, dtstart=date(2001, 1, 1), until=date(2005, 1, 1)))
> ```
> 
> not with a generator.
> 
> If you think [the docs](https://github.com/adamchainz/flake8-comprehensions#c416-unnecessary-listset-comprehension---rewrite-using-listset) could be improved, please make a suggestion!

Makes sense, thank you!
