### ISSUE TITLE
C400 C416 loop

### ISSUE THREAD

**Issue by viivanofu** [adamchainz/flake8-comprehensions#454]
### Python Version

3.10.8

### flake8 Version

5.0.4

### Package Version

latest

### Description

`my_list = [i for i in range(0, 500)]` reports as **C416**
but after rewriting as
`my_list = list(i for i in range(0, 500))` reports as **C400**
that leads to report loop

**Comment by viivanofu** [comment]
I've solved it just by turning off the C416, but it is an issue anyways

**Comment by adamchainz** [comment]
You’re missing the point of C416, it’s telling you to write `list(range(0, 500))`.

Docs: https://github.com/adamchainz/flake8-comprehensions#c416-unnecessary-listset-comprehension---rewrite-using-listset

**Comment by viivanofu** [comment]
Thank you kindly!
