### ISSUE TITLE
C402 false positive with extra kwargs to dict()

### ISSUE THREAD

**Issue by andersk** [adamchainz/flake8-comprehensions#457]
### Python Version

3.10.7

### flake8 Version

5.0.4

### Package Version

3.10.0

### Description

flake8-compehensions gives “C402 Unnecessary generator - rewrite as a dict comprehension” on both of these lines. But the second cannot be rewritten as a dict comprehension due to the extra keyword argument `c`, so only the first should be an error.

```python
dict((a, b) for a, b in [("a", "b")])
dict(((a, b) for a, b in [("a", "b")]), c="d")
```

([Examples in real code](https://github.com/zulip/zulip/blob/925fa4ca50215e7d4ba0e7d72b1b77ad3f0b5a38/zerver/lib/exceptions.py#L114-L123).)

**Comment by adamchainz** [comment]
Fixed in #458, released in 3.10.1. Thanks for the report.
