### ISSUE TITLE
Feature request: Inverse of C417: check for `f(x) for x in iterable`

### ISSUE THREAD

**Issue by GideonBear** [adamchainz/flake8-comprehensions#462]
### Description

(Thanks for `flake8-comprehensions`, it's a good plugin)
Check for `f(x) for x in iterable` in any comprehension, and suggest replacing it with `map(f, iterable)`.
This is not objectively better like some other rules are, but IMO this is cleaner.

**Comment by adamchainz** [comment]
Personally I find the generic syntax more readable, it means one less function the reader has to know about. So I'm not sure right now, maybe if others weigh in we could add this.

**Comment by GideonBear** [comment]
Sorry, what do you mean with "the generic syntax"? The comprehensions?
This could also be an optional (enable in the config, disabled by default) rule, because I think this would be a good addition to this package, even if this is a thing that you or other people disagree with.

The same thing applies to `x for x in iterable if condition(x)` and `f(x) for x in iterable if condition(x)` for `filter(condition, iterable)` and `map(f, filter(condition, iterable))`
IMO `map`+`filter` is ugly, but that could also be an optional rule.

**Comment by GideonBear** [comment]
The same could apply in reverse, you could make a rule that detects usage of `map` and `filter` and suggests converting it to a generator expression/list comprehension depending on if you wrap it in `list` or not

**Comment by adamchainz** [comment]
> Sorry, what do you mean with "the generic syntax"? The comprehensions?

Yes, it's generic in that you can use list comprehensions for many different purposes.

Anyway I don't think we can consider the conversion between `map` and comprehensions, because `map` is lazy whilst comprehensions aren't. I have removed rules in the past due to changing laziness, since it's not always safe to do.

**Comment by GideonBear** [comment]
> because map is lazy whilst comprehensions

This is not true for generator expressions, only for list/set comprehensions.
Anyway, I'm fine with this plugin not supporting that, both ways are pretty opinionated.

**Comment by adamchainz** [comment]
> This is not true for generator expressions, only for list/set comprehensions.

Ah yes, that's true. But still I think `map` isn't cleaner, as you say, it's opinion at that point.
