### ISSUE TITLE
Extend to C416 to dict comprehensions

### ISSUE THREAD

**Issue by Skylion007** [adamchainz/flake8-comprehensions#489]
### Description

```python
keys = range(100)
values = range(100)

out = {a:b for a,b in zip(keys, values)}
```

This is likely inefficient compared to the follow which does not need to unpack / repack the tuple. 
```python
out = dict(zip(keys, values))
 ```
 
This is essentially an extension of C416 to handle dict comprehensions as well. The version without the dict comprehension should be identical to the original code, just potentially more efficient.

**Comment by adamchainz** [comment]
Is `zip` required to be sure of this? Can't we suggest to rewrite more generally:

```diff
-{a: b for a, b in _}
+dict(_)
```

For *any* `_` ? I think so...

Would you like to work on a PR here?

**Comment by Skylion007** [comment]
@adamchainz Yep, any iterable would work. This was easier to add than I thought: https://github.com/adamchainz/flake8-comprehensions/pull/490
