### ISSUE TITLE
Should recommend list() be replaced with []

### ISSUE THREAD

**Issue by jdufresne** [adamchainz/flake8-comprehensions#49]
test.py

```python
l = list()
print(l)
```

```
$ flake8 test.py
```

Actual: (no output)

Expected: I think perhaps this should output that `list()` is better written as `[]`. Same is true for `dict()` -> `{}`.

I see this as being very similar to "Unnecessary generator - rewrite as a list comprehension.", except it is a literal instead of a comprehension.

What do you think?

Noticed while running against the Django codebase:

https://github.com/django/django/blob/f3427ccb25806bb062becad0d6a0904930b36635/tests/model_inheritance/test_abstract_inheritance.py#L321

**Comment by adamchainz** [comment]
I guess, but also taking the library a bit out of its remit of "comprehensions". I wish I gave it a more generic name 🤔
