### ISSUE TITLE
Feature Request: Detect dictionary comprehensions with constant values

### ISSUE THREAD

**Issue by tjkuson** [adamchainz/flake8-comprehensions#552]
### Description

Hi! Thanks for this helpful tool.

I'm working with code that has a lot of 

```python
{elt: None for elt in foo}
```

which is slower and (IMO) harder to read than

```python
dict.fromkeys(foo)
```

Would there be interest in a rule that checks for dictionary comprehensions with constant values?

This has rule has been accepted by [another project](https://github.com/astral-sh/ruff/issues/9592) and it was suggested to me that I create an issue here too.

**Comment by adamchainz** [comment]
Yeah, I would like that here too. I don’t have time to work on it right now, but I’d accept a PR adding it.

**Comment by tjkuson** [comment]
I'll open a PR later today.
