### ISSUE TITLE
Add support for next() to builtins checked?

### ISSUE THREAD

**Issue by pope1ni** [adamchainz/flake8-comprehensions#56]
`next()` will happily take a generator instead of a list or tuple.

Would it also be possible to recommend simplifications such as:

```diff
-[x for x in y if x == z][0]
+next(x for x in y if x == z)
```

The main problem here would be the change of exception from `IndexError` to `StopIteration` if there are no elements in the iterable.

**Comment by pope1ni** [comment]
In addition, constructs of the form `next(iter(<comprehension>))` and `next(iter(<generator>))` could be simplified to `next(<generator>)`...

**Comment by adamchainz** [comment]
Can you split this into three issues since you've recognized three different things in a stream of consciousness?

**Comment by pope1ni** [comment]
Split into #57, #58 and #59. Also added #60 and #61 as I thought of them.
