### ISSUE TITLE
Add new rule for next(<comprehension>)

### ISSUE THREAD

**Issue by pope1ni** [adamchainz/flake8-comprehensions#57]
Suggest change from `next(<comprehension>)` to `next(<generator>)` as [`next()`](https://docs.python.org/3/library/functions.html#next) will happily consume a generator. Need to be aware of the `default` argument in which case the generator will need still to be wrapped in parentheses.

**Comment by adamchainz** [comment]
This can just be added to C407 I think.

**Comment by adamchainz** [comment]
As noted in #108, `next` can't take a list comprehension in the first place, so this isn't necessary :)
