### ISSUE TITLE
Add new rule for <comprehension>[0]

### ISSUE THREAD

**Issue by pope1ni** [adamchainz/flake8-comprehensions#59]
Suggest change from `<comprehension>[0]` `next(<generator>)`, e.g.

```diff
-[x for x in y if x == z][0]
+next(x for x in y if x == z)
```

This may be a bad idea as there would be the change of exception from `IndexError` to `StopIteration` if there are no elements returned by the generator. But it could also be possible to do the following to avoid the overhead of list creation:

```diff
-try:
-    v = [x for x in y if x == z][0]
-except IndexError:
-    v = 123
+v = next((x for x in y if x == z), 123)
```
This may not be feasible as it would be quite complicated to implement sanely.

**Comment by adamchainz** [comment]
I agree this is too complicated, so closing.
