### ISSUE TITLE
Split C400 by type

### ISSUE THREAD

**Issue by danpalmer** [adamchainz/flake8-comprehensions#6]
To eliminate confusion between dict and set comprehensions, our style guideline is that we do not use set literals or comprehensions, and instead use the explicit `set()` constructor.

For this reason, I'd like to be able to ignore `C400` warnings about set comprehensions, but keep them for dict/list comprehensions.

What do you think about splitting `C400` into 3 separate warnings? This appears to be a fairly common sort of thing to do, i.e. if you see `E127` and `E128`, they are both "you indented it wrong", but in opposite directions, to allow more fine-tuning.

Would you accept a PR for this if I implemented it?

**Comment by adamchainz** [comment]
Yup, one error code per type would be fine in this case. Since the library is so young you can just renumber all the existing codes.

Just beware I won't split #5 as it will apply to many builtins such as `sum`, `all`, `any`, etc.
